"""Public contracts for bounded permission-aware retrieval."""

from incident_diagnostic_api.retrieval.content_controls import (
    CONTENT_CONTROL_VERSION,
    ContentControlDisposition,
    ContentControlResult,
    ContentRiskCategory,
    ContentSignal,
    ContentTrustLabel,
    ContextItemAssessment,
    ControlledContextItem,
    detect_content_signals,
    inspect_context,
)
from incident_diagnostic_api.retrieval.context import (
    CONTEXT_BUDGET_VERSION,
    ContextBudget,
    ContextBundle,
    ContextConstructionResult,
    ContextDisposition,
    ContextInsufficiency,
    ContextInsufficiencyCode,
    ContextItem,
    build_context,
)
from incident_diagnostic_api.retrieval.corpus import (
    SyntheticEvidenceCorpus,
    calculate_content_hash,
)
from incident_diagnostic_api.retrieval.embeddings import (
    EMBEDDING_DIMENSIONS,
    EMBEDDING_VERSION,
    EmbeddingVector,
    cosine_similarity,
    embed_text,
)
from incident_diagnostic_api.retrieval.enums import (
    EvidenceLifecycleStatus,
    EvidenceSourceKind,
    RetrievalAbstentionCode,
    RetrievalDisposition,
    RetrievalMethod,
)
from incident_diagnostic_api.retrieval.hybrid import (
    HybridRetrievalConfig,
    calculate_hybrid_score,
    calculate_reciprocal_rank_score,
    normalize_candidate_scores,
    retrieve_hybrid,
)
from incident_diagnostic_api.retrieval.keyword import (
    calculate_keyword_score,
    retrieve_keywords,
    tokenize_keywords,
)
from incident_diagnostic_api.retrieval.models import (
    Citation,
    EvidenceChunk,
    EvidenceDocument,
    EvidenceSource,
    RetrievalAbstention,
    RetrievalCandidate,
    RetrievalQuery,
    RetrievalResult,
)
from incident_diagnostic_api.retrieval.vector import (
    VECTOR_INDEX_VERSION,
    SyntheticVectorIndex,
    VectorIndexEntry,
    build_vector_index,
    retrieve_vectors,
)

__all__ = [
    "CONTENT_CONTROL_VERSION",
    "CONTEXT_BUDGET_VERSION",
    "EMBEDDING_DIMENSIONS",
    "EMBEDDING_VERSION",
    "VECTOR_INDEX_VERSION",
    "Citation",
    "ContentControlDisposition",
    "ContentControlResult",
    "ContentRiskCategory",
    "ContentSignal",
    "ContentTrustLabel",
    "ContextBudget",
    "ContextBundle",
    "ContextConstructionResult",
    "ContextDisposition",
    "ContextInsufficiency",
    "ContextInsufficiencyCode",
    "ContextItem",
    "ContextItemAssessment",
    "ControlledContextItem",
    "EmbeddingVector",
    "EvidenceChunk",
    "EvidenceDocument",
    "EvidenceLifecycleStatus",
    "EvidenceSource",
    "EvidenceSourceKind",
    "HybridRetrievalConfig",
    "RetrievalAbstention",
    "RetrievalAbstentionCode",
    "RetrievalCandidate",
    "RetrievalDisposition",
    "RetrievalMethod",
    "RetrievalQuery",
    "RetrievalResult",
    "SyntheticEvidenceCorpus",
    "SyntheticVectorIndex",
    "VectorIndexEntry",
    "build_context",
    "build_vector_index",
    "calculate_content_hash",
    "calculate_hybrid_score",
    "calculate_keyword_score",
    "calculate_reciprocal_rank_score",
    "cosine_similarity",
    "detect_content_signals",
    "embed_text",
    "inspect_context",
    "normalize_candidate_scores",
    "retrieve_hybrid",
    "retrieve_keywords",
    "retrieve_vectors",
    "tokenize_keywords",
]
