"""Public Phase 7 tool contracts, mocks, dispatcher, and consistency evidence."""

from incident_diagnostic_api.tools.contracts import (
    EXPECTED_TOOL_ERROR_CATEGORIES,
    EXPECTED_TOOL_ERROR_RETRYABILITY,
    TOOL_ENVELOPE_VERSION,
    ToolError,
    ToolErrorCategory,
    ToolErrorCode,
    ToolRequest,
    ToolResult,
    ToolResultStatus,
)
from incident_diagnostic_api.tools.dispatcher import (
    TOOL_DISPATCHER_VERSION,
    ToolDispatchOutcome,
    dispatch_deterministic_local_tool_request,
)
from incident_diagnostic_api.tools.evidence import (
    TOOL_OUTCOME_EVIDENCE_VERSION,
    ToolOutcomeConsistencyStatus,
    ToolOutcomeEvidence,
    ToolOutcomeEvidenceError,
    ToolOutcomeEvidenceErrorCode,
    ToolOutcomeKind,
    build_deterministic_tool_outcome_evidence,
)
from incident_diagnostic_api.tools.mock import (
    MOCK_TOOL_RUNTIME_VERSION,
    build_deterministic_mock_tool_error,
    build_deterministic_mock_tool_result,
)
from incident_diagnostic_api.tools.registry import (
    DEFAULT_TOOL_REGISTRY,
    TOOL_CONTRACT_VERSION,
    TOOL_REGISTRY_VERSION,
    ToolApprovalRequirement,
    ToolCapability,
    ToolDefinition,
    ToolIdempotencyRequirement,
    ToolName,
    ToolRegistry,
    ToolRiskTier,
    ToolSideEffect,
    build_default_tool_registry,
)

__all__ = [
    "DEFAULT_TOOL_REGISTRY",
    "EXPECTED_TOOL_ERROR_CATEGORIES",
    "EXPECTED_TOOL_ERROR_RETRYABILITY",
    "MOCK_TOOL_RUNTIME_VERSION",
    "TOOL_CONTRACT_VERSION",
    "TOOL_DISPATCHER_VERSION",
    "TOOL_ENVELOPE_VERSION",
    "TOOL_OUTCOME_EVIDENCE_VERSION",
    "TOOL_REGISTRY_VERSION",
    "ToolApprovalRequirement",
    "ToolCapability",
    "ToolDefinition",
    "ToolDispatchOutcome",
    "ToolError",
    "ToolErrorCategory",
    "ToolErrorCode",
    "ToolIdempotencyRequirement",
    "ToolName",
    "ToolOutcomeConsistencyStatus",
    "ToolOutcomeEvidence",
    "ToolOutcomeEvidenceError",
    "ToolOutcomeEvidenceErrorCode",
    "ToolOutcomeKind",
    "ToolRegistry",
    "ToolRequest",
    "ToolResult",
    "ToolResultStatus",
    "ToolRiskTier",
    "ToolSideEffect",
    "build_default_tool_registry",
    "build_deterministic_mock_tool_error",
    "build_deterministic_mock_tool_result",
    "build_deterministic_tool_outcome_evidence",
    "dispatch_deterministic_local_tool_request",
]
