"""Deterministic local runtime for the bounded diagnostic workflow."""

from incident_diagnostic_api.runtime.budgets import (
    RuntimeBudgetExceededError,
    RuntimeBudgetLimits,
    ensure_retry_budget,
    ensure_step_budget,
    increment_stage_retry_counts,
)
from incident_diagnostic_api.runtime.checkpoints import (
    GENESIS_CHECKPOINT_HASH,
    CheckpointNotFoundError,
    CheckpointVersionConflictError,
    InMemoryCheckpointStore,
    RuntimeCheckpoint,
    calculate_checkpoint_hash,
    hash_runtime_state,
    verify_checkpoint_history,
)
from incident_diagnostic_api.runtime.engine import (
    DeterministicRuntimeEngine,
    RuntimeExecutionStoppedError,
    RuntimeRetryRequest,
    RuntimeStartResult,
    RuntimeStepResult,
    RuntimeTransitionContext,
)
from incident_diagnostic_api.runtime.enums import (
    ACTIVE_STATES,
    INITIAL_STATES,
    STATE_TYPES,
    TERMINAL_STATES,
    FailureClassification,
    RuntimeReasonCode,
    RuntimeState,
    RuntimeStateType,
    TransitionCommand,
    is_terminal_state,
    state_type,
)
from incident_diagnostic_api.runtime.errors import (
    InvalidTransitionError,
    RuntimeTransitionError,
    TerminalStateTransitionError,
)
from incident_diagnostic_api.runtime.models import (
    RuntimeStateRecord,
    StageRetryCount,
)
from incident_diagnostic_api.runtime.replay import (
    ReplayIntegrityError,
    ReplayResult,
    ReplayStep,
    replay_checkpoint_history,
)
from incident_diagnostic_api.runtime.stops import (
    TERMINAL_DISPOSITIONS,
    StopCondition,
    StopDecision,
    StopDisposition,
    evaluate_pre_transition_stop,
    evaluate_retry_stop,
)
from incident_diagnostic_api.runtime.traces import (
    STATE_STAGES,
    TARGET_OUTCOMES,
    TraceGenerationError,
    build_genesis_trace_event,
    build_retry_trace_event,
    build_stop_trace_event,
    build_transition_trace_event,
)
from incident_diagnostic_api.runtime.transitions import (
    TRANSITIONS,
    TransitionDefinition,
    allowed_commands,
    is_transition_allowed,
    resolve_transition,
)

__all__ = [
    "ACTIVE_STATES",
    "GENESIS_CHECKPOINT_HASH",
    "INITIAL_STATES",
    "STATE_STAGES",
    "STATE_TYPES",
    "TARGET_OUTCOMES",
    "TERMINAL_DISPOSITIONS",
    "TERMINAL_STATES",
    "TRANSITIONS",
    "CheckpointNotFoundError",
    "CheckpointVersionConflictError",
    "DeterministicRuntimeEngine",
    "FailureClassification",
    "InMemoryCheckpointStore",
    "InvalidTransitionError",
    "ReplayIntegrityError",
    "ReplayResult",
    "ReplayStep",
    "RuntimeBudgetExceededError",
    "RuntimeBudgetLimits",
    "RuntimeCheckpoint",
    "RuntimeExecutionStoppedError",
    "RuntimeReasonCode",
    "RuntimeRetryRequest",
    "RuntimeStartResult",
    "RuntimeState",
    "RuntimeStateRecord",
    "RuntimeStateType",
    "RuntimeStepResult",
    "RuntimeTransitionContext",
    "RuntimeTransitionError",
    "StageRetryCount",
    "StopCondition",
    "StopDecision",
    "StopDisposition",
    "TerminalStateTransitionError",
    "TraceGenerationError",
    "TransitionCommand",
    "TransitionDefinition",
    "allowed_commands",
    "build_genesis_trace_event",
    "build_retry_trace_event",
    "build_stop_trace_event",
    "build_transition_trace_event",
    "calculate_checkpoint_hash",
    "ensure_retry_budget",
    "ensure_step_budget",
    "evaluate_pre_transition_stop",
    "evaluate_retry_stop",
    "hash_runtime_state",
    "increment_stage_retry_counts",
    "is_terminal_state",
    "is_transition_allowed",
    "replay_checkpoint_history",
    "resolve_transition",
    "state_type",
    "verify_checkpoint_history",
]
